version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: macroesthetics-pg
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - .db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
