version: '3.1'

services:
  postgres:
    image: postgres:14-alpine
    container_name: macroesthetics-pg
    restart: always
    environment:
      POSTGRES_BD: ${POSTGRES_BD}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"